
# General settings
title: "AFKology | The most precious moments in life happen offline."
title-ro: "AFKology | Cele mai frumoase momente din viata se intampla offline."
email: office@afkology.com
description: "The most precious moments in life happen offline. AFKology is a remembrance of that."
description-ro: "Cele mai frumoase momente din viata se intampla offline. AFKology este o amintire a acestui lucru."
keywords: "afkology, travel, cinematic travel, travel ideas, travel guide, food buide, travel europe, restaurants, places to visit"
keywords-ro: "afkology, calatorii, idei de calatorie, restaurante, calatorii in europa, locuri de vizitat"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.afkology.com"
permalink: /:title/
logo: '/assets/images/logo-autumn-afk.png'
logo-height: 130
logo-width: 230

# Social platforms
youtube: https://www.youtube.com/channel/UC6cO4CO-T5PGkeXWc8Sf1lw
medium: https://medium.com/@afkology
instagram: https://www.instagram.com/afkology/
facebook: https://www.facebook.com/afkology/
tiktok: https://www.tiktok.com/@afkology

# Show posts date on homepage
show-posts-date: false 

# Pinterest settings
enable-pinterest-on-image-hover: true
pinterest-site-key: a6fc09c0694f88b02ffdc31fd0e107ae
pinterest: https://pinterest.com/afkology

# Footer settings
footer-color: ffffff
show-theme-watermark: true

# Track traffic
google-tag-manager-id: GTM-PF6ZFZZ

# Pagination settings
pagination:
  enabled: true
  per_page: 9
  permalink: '/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Build settings
plugins:
  - jekyll-feed
  # - jekyll-sitemap
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-responsive-image

jekyll-minifier:
  uglifier_args:
    harmony: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vscode
  - clean.bat
  - build.bat
  - git-push.bat
  - develop.bat
  - README.md

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 600
    - width: 800
    - width: 1600
  extra_images:
  - assets/images/posts/*/*.webp