
# General settings
title: "AFKology | The most precious moments in life happen offline."
email: office@afkology.com
description: "The most precious moments in life happen offline. AFKology is a remembrance of that."
keywords: "afkology, travel, drone, photography, cinematic, travel ideas"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.afkology.com"
permalink: /:title/
logo: '/assets/images/logo_v1.0.webp'
logo-height: 130
logo-width: 290

# Social platforms
youtube: https://www.youtube.com/channel/UC6cO4CO-T5PGkeXWc8Sf1lw
medium: https://medium.com/@afkology
instagram: https://www.instagram.com/afkology/
facebook: https://www.facebook.com/afkology/
tiktok: https://www.tiktok.com/@afkology

# Show posts date on homepage
show-posts-date: false 

# Pinterest settings
enable-pinterest-on-image-hover: true
pinterest-site-key: a6fc09c0694f88b02ffdc31fd0e107ae
pinterest: https://pinterest.com/afkology

# Footer settings
footer-color: ffffff
show-theme-watermark: true

# Track traffic
google-tag-manager-id: GTM-PF6ZFZZ

# Pagination settings
# paginate: 9
# paginate_path: "/:num/"

pagination:
  enabled: true
  per_page: 9
  permalink: '/:num/'
  category: 'Main'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-paginate-v2

jekyll-minifier:
  uglifier_args:
    harmony: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vscode
  - clean.bat
  - build.bat
  - git-push.bat
  - develop.bat
  - README.md
